<div style="width: 1000px; margin: auto !important; display: flex; flex-direction: column; gap: 4rem; padding: 2rem;">
<div style="display: flex; flex-direction: row; align-items: center; gap: 20px;">
<div><img src="https://images.unsplash.com/39/lIZrwvbeRuuzqOoWJUEn_Photoaday_CSD%20%281%20of%201%29-5.jpg?q=80&amp;w=2070&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="" width="450px" height="auto" /></div>
<div>
<h3>Unlock Your Career Potential with Us!</h3>
<p>We understand the importance of finding the right job &ndash; a position that not only matches your skills but also aligns with your passion and aspirations.</p>
</div>
</div>
<div style="display: flex; flex-direction: row; align-items: center; gap: 20px;">
<div>
<h3>Unlock Your Career Potential with Us!</h3>
<p>We understand the importance of finding the right job &ndash; a position that not only matches your skills but also aligns with your passion and aspirations.</p>
</div>
<div><img src="https://images.unsplash.com/39/lIZrwvbeRuuzqOoWJUEn_Photoaday_CSD%20%281%20of%201%29-5.jpg?q=80&amp;w=2070&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="" width="450px" height="auto" /></div>
</div>
</div>