<div class="contentBody">
<div class="hero">
<div class="heroText">
<h1><strong>Unlock Your Career Potential with Us!</strong></h1>
<p>We understand the importance of finding the right job &ndash; a position that not only matches your skills but also aligns with your passion and aspirations.</p>
</div>
<div class="heroImg"><img src="https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&amp;w=2070&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="" width="500px" height="auto" /></div>
</div>
</div>