<div class="modal-content" id="<?php echo $this->id ?>" data-melisKey="<?php echo $this->melisKey; ?>">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <?php
                        $ctr = 0;
                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                            $active = ($ctr++) ? '' : 'active';
                            $tabId = "{$this->id}_{$menuConfig['conf']['id']}";
                            $tabIcon = !empty($menuConfig['conf']['icon']) ? $menuConfig['conf']['icon'] : 'pencil';
                            $tabName = $menuConfig['conf']['name'];

                            echo "<li class='{$active}'><a href=''>{$tabName}</a></li>";
                        }
                        ?>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class='tab-content'>
                        <?php
                        $ctr = 0;
                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                            $tabId = $this->id . '_' . $menuConfig['conf']['id'];

                            $active = ($ctr++) ? '' : 'active';
                            echo '<div class="tab-pane ' . $active . '" id="' . $tabId . '">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    ' . $this->$keyConfig . '
                                                </div>
                                            </div>
                                        </div>';
                        }
                        ?>
                        <div align="right">
                            <a data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i>
                                close
                            </a>
                            <a id="btnSaveJob" class="btn btn-success" data-id="<?php echo $this->id ?>"><i
                                    class="fa fa-save"></i>
                                save
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>